---
abstract: 'Archive::Any wrapper around Archive::Rar'
author:
  - 'Dmitriy V. Simonov, C<< <dsimonov at gmail.com> >>'
  - 'Dmitriy V. Simonov <dsimonov@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  lib::abs: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Archive-Any-Plugin-Rar
no_index:
  directory:
    - inc
    - t
requires:
  Archive::Any: 0
  Archive::Rar: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
